import = [
  "~/.config/alacritty/themes/themes/xterm.toml"
]
live_config_reload = true

[window]
decorations = "None"
startup_mode = "Maximized"
opacity = 0.92
blur = true

[font]
size = 20

[font.normal]
family = "BerkeleyMono Nerd Font Mono"
